name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH into VM and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            set -e
            cd /home/rachadyannarotama/frontend

            echo "=== Pull latest code ==="
            git pull origin main

            echo "=== Install deps ==="
            npm install --legacy-peer-deps

            echo "=== Build production ==="
            rm -rf build
            npm run build

            echo "=== Deploy to Nginx ==="
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            echo "=== Restart Nginx ==="
            sudo systemctl restart nginx

            echo "=== Deployment Success ==="